### ISSUE TITLE
clicking on message link beside the user takes to empty page 

### ISSUE THREAD

**Issue by CDSLabs** [pushyachandra/Inventory-Marketplace#19]
1) sent a message to the seller after logging in
2) clicked on the seller in left navigation to see the message thread 
3) clicked on message tab, page goes empty and becomes non-navigable

**Comment by pushyachandra** [comment]
Thank you for letting us know about the bug, we have verified this from our end and have identified this issue to be present, our team is currently working on fixing this bug and we will let you know after it has been fixed and redeployed.

Quick Fix: When the page becomes non-navigable, please refresh the page it will load the data back to it. 

We will fix the bug and deploy the changes soon.

**Comment by pushyachandra** [comment]
The bug has been identified and it has been fixed, the fix will be deployed shortly

**Comment by Abhi0496** [comment]
Latest code with bug fix has been deployed and its working as per expectation.
